const intents = {
  firmativo: [
    "si",
    "correcto",
    "afirmativo",
    "asi es",
    "yes",
    "esta bien",
    "sii",
    "tienes razon",
    "me parece bien",
    "eso es correcto",
    "es verdad",
    "cierto",
    "bien",
    "estoy de acuerdo",
  ],
  cuentaChiste: [
    "hey",
    "hola",
    "oye",
    "me puedes contar un chiste",
    "un chiste",
    "algo gracioso",
    "un chiste que quiero reir",
    "animame",
    "un chistecito",
    "chistes para reirme",
    "bromas",
    "chistes",
    "cosas graciosas",
    "me puedes contar",
    "cuentame",
    "cuentate",
    "comparte",
    "quiero que me cuentes",
    "deseo que me cuentes",
    "cuenta",
    "matame de risa con",
    "sabes",
    "quiero reir",
    "por favor",
  ],
  desconocido: [
    "hey",
    "hola",
    "como te llamas",
    "que hora es",
    "de donde eres",
    "que te gusta comer",
    "eres bonita",
    "te gusta cocinar",
    "que harias si fueras grande",
    "sabes ingles",
    "sabes hablar frances",
    "alguna vez te has enamorado",
    "cuestiones asociadas con la capacidad de pensar y reflexionar",
    "el origen de la filosofía",
    "como puede ser el hombre feliz en el mundo",
    "que es lo real",
    "crees en dios",
    "tienes alguna religion",
    "que piensas de el ser humano",
    "que sabes hacer",
    "defineme la existencia",
    "preguntas filosoficas",
    "analisis de la realidad",
    "cualquier pregunta",
    "hablame de la vida",
    "hablame de lo que sea",
    "cual es el origen del universo",
    "cuentame de la vida",
    "informame de la vida",
    "de lo que sea",
    "habla me de algo",
    "de donde vienes y a donde vas",
    "como esta el clima",
    "como esta el cielo",
    "como esta el precio del dolar",
    "cuanto pesas",
    "cuantos anos tienes",
    "sabes sumar",
    "cuanto es dos mas dos",
    "cuanto es 1 mas 1",
    "cuanto es 1 1",
    "cuanto es 3 3",
  ],
  despedida: [
    "chau",
    "adios",
    "me despido",
    "cuidate chau",
    "hasta luego",
    "hablamos despues",
    "cambio y fuera",
    "buenas noches",
    "ya me voy",
    "ya me quito chau",
  ],
  gracias: [
    "gracias",
    "muchas gracias",
    "te lo agradesco",
    "agradecida",
    "agradecido",
    "de verdad gracias",
    "thank you",
    "en serio gracias",
    "muchisimas gracias",
    "thanks",
    "se agradece",
    "grax",
    "oye gracias",
    "thank you very much",
    "super gracias",
    "gracias de verdad",
    "lo maximo gracias",
  ],
  negativo: [
    "no",
    "nope",
    "negativo",
    "asi no es",
    "incorrect",
    "incorrecto",
    "no quiero eso",
    "no esta bien",
    "no",
    "nope",
    "negativo",
    "asi no es",
    "incorrect",
    "incorrecto",
    "no quiero eso",
    "no esta bien",
  ],
  greeting: [
    "hola",
    "buenos días",
    "buenas tardes",
    "buenas noches",
    "¿qué tal?",
    "hola, ¿cómo estás?",
    "¡hey!",
    "¿qué pasa?",
  ],
  goodbye: [
    "adiós",
    "hasta luego",
    "nos vemos",
    "hasta la próxima",
    "cuídate",
    "chao",
    "me despido",
    "hasta pronto",
  ],
  thanks: [
    "gracias",
    "muchas gracias",
    "te lo agradezco",
    "gracias de antemano",
    "agradecido",
    "mil gracias",
    "gracias por todo",
    "infinitas gracias",
  ],
  product_inquiry: [
    "cuéntame sobre tus productos",
    "¿qué vendes?",
    "información de productos",
    "¿qué puedo comprar?",
    "muéstrame tus productos",
    "¿qué ofertas tienen?",
    "productos disponibles",
    "quiero saber más sobre lo que venden",
  ],
  order_status: [
    "¿dónde está mi pedido?",
    "estado de mi pedido",
    "rastrear mi pedido",
    "seguimiento de pedido",
    "actualización de pedido",
    "información de mi pedido",
    "¿mi pedido ya fue enviado?",
    "quiero detalles de mi pedido",
  ],
  return_policy: [
    "política de devoluciones",
    "¿cómo devolver un producto?",
    "proceso de devolución",
    "¿puedo devolver?",
    "devoluciones",
    "¿tienen garantía?",
    "quiero hacer una devolución",
    "información sobre devoluciones",
  ],
  payment_methods: [
    "opciones de pago",
    "¿cómo puedo pagar?",
    "métodos de pago",
    "pagos disponibles",
    "¿aceptan tarjeta de crédito?",
    "¿puedo pagar con PayPal?",
    "¿hay cuotas sin interés?",
    "formas de pago aceptadas",
  ],
  support_contact: [
    "contactar soporte",
    "¿cómo contactar al soporte?",
    "contacto del servicio al cliente",
    "información de soporte",
    "atención al cliente",
    "necesito ayuda",
    "¿dónde puedo llamar?",
    "¿tienen chat de soporte?",
  ],
  business_hours: [
    "horarios de atención",
    "horarios de trabajo",
    "¿cuándo están abiertos?",
    "horario de apertura",
    "horarios de la tienda",
    "¿qué días trabajan?",
    "¿abren los fines de semana?",
    "horarios y días laborales",
  ],
  promotions: [
    "promociones actuales",
    "¿tienen ofertas?",
    "productos en descuento",
    "¿hay rebajas?",
    "quiero saber sobre promociones",
    "¿cuáles son las ofertas de hoy?",
  ],
  account_help: [
    "necesito ayuda con mi cuenta",
    "¿cómo creo una cuenta?",
    "olvidé mi contraseña",
    "problemas con mi cuenta",
    "¿cómo actualizo mi información personal?",
    "quiero cambiar mi correo registrado",
    "¿cómo elimino mi cuenta?",
  ],
  feedback: [
    "quiero dar mi opinión",
    "¿dónde puedo dejar un comentario?",
    "tengo una queja",
    "me gustaría dar una sugerencia",
    "¿cómo puedo calificar su servicio?",
    "tengo un comentario sobre su producto",
  ],
  technical_support: [
    "necesito soporte técnico",
    "mi producto no funciona",
    "¿cómo soluciono un error?",
    "problemas técnicos",
    "mi dispositivo no enciende",
    "¿cómo actualizo el software?",
    "problemas de conectividad",
  ],
  product_recommendation: [
    "¿qué producto me recomiendan?",
    "necesito ayuda para elegir un producto",
    "¿cuál es el mejor producto para mí?",
    "sugerencias de productos",
    "recomendaciones según mis necesidades",
  ],
  order_cancellation: [
    "quiero cancelar mi pedido",
    "¿cómo cancelo una compra?",
    "cancelación de pedido",
    "anular mi pedido",
    "¿es posible cancelar un pedido ya hecho?",
    "cancelar una orden",
    "quiero detener mi compra",
    "¿cómo puedo anular la transacción?",
    "¿hay penalización por cancelar?",
  ],
  shipping_info: [
    "quiero saber sobre el envío",
    "¿cuánto cuesta el envío?",
    "opciones de envío disponibles",
    "¿envían a mi país?",
    "información sobre entregas internacionales",
    "¿cuánto tarda en llegar?",
    "envíos urgentes",
    "¿puedo rastrear mi envío?",
    "políticas de envío",
    "¿hay envío gratuito?",
    "información de envío",
    "¿cómo hacen los envíos?",
    "métodos de envío",
    "opciones de entrega",
    "¿cuánto tarda el envío?",
    "¿envían a mi ciudad?",
    "costos de envío",
    "¿cómo puedo recibir mi pedido?",
  ],
  promotions_and_discounts: [
    "¿tienen descuentos?",
    "promociones actuales",
    "¿cómo consigo un cupón?",
    "ofertas especiales",
    "¿hay rebajas esta semana?",
    "productos en oferta",
    "¿cómo aplico un descuento?",
    "¿tienen programas de fidelidad?",
    "¿hay beneficios para clientes frecuentes?",
  ],
  weather_inquiry: [
    "¿cómo está el clima?",
    "¿qué tal el tiempo?",
    "¿va a llover hoy?",
    "dime sobre el clima",
    "pronóstico del tiempo",
    "¿qué temperatura hace?",
  ],
  motivational_quote: [
    "dame una frase motivacional",
    "quiero una cita inspiradora",
    "anímame con una frase",
    "una frase para inspirarme",
    "quiero motivarme",
    "¿me das motivación?",
  ],
  fun_fact: [
    "dime un dato curioso",
    "quiero aprender algo interesante",
    "un hecho divertido",
    "cuéntame algo que no sepa",
    "¿sabes algo curioso?",
    "sorpréndeme con un dato",
  ],
  trivia_question: [
    "dame una pregunta de trivia",
    "quiero una pregunta interesante",
    "hazme una pregunta difícil",
    "¿qué pregunta de trivia tienes?",
    "preguntas curiosas por favor",
  ],
  joke_request: [
    "dime otro chiste",
    "hazme reír de nuevo",
    "otro chiste por favor",
    "más bromas",
    "dame más humor",
  ],
  health_tips: [
    "dame un consejo de salud",
    "¿cómo puedo estar saludable?",
    "tips para una vida sana",
    "¿qué puedo hacer para sentirme mejor?",
    "dime algo sobre salud",
  ],
  cooking_recipe: [
    "dame una receta fácil",
    "¿cómo preparo un postre rápido?",
    "receta sencilla por favor",
    "enséñame a cocinar algo",
    "quiero aprender una receta nueva",
  ],
  story_request: [
    "cuéntame una historia",
    "quiero escuchar un cuento",
    "una historia corta",
    "¿puedes contarme algo interesante?",
    "cuéntame algo divertido o sorprendente",
    "quiero un relato",
  ],
  language_learning: [
    "enséñame inglés",
    "¿cómo se dice en francés?",
    "quiero aprender un idioma",
    "¿cómo se pronuncia?",
    "traduce esto por favor",
    "dame frases comunes en inglés",
  ],
  workout_tips: [
    "¿cómo empiezo a hacer ejercicio?",
    "dame una rutina de ejercicios",
    "quiero tips para mantenerme activo",
    "¿qué ejercicios son buenos para principiantes?",
    "dame ideas para entrenar en casa",
  ],
  travel_tips: [    
    "¿qué empacar para un viaje?",
    "lugares recomendados para visitar",
    "quiero planear unas vacaciones",
    "¿cómo puedo viajar más barato?",
    "dame consejos para viajar",
    "¿qué necesito para mi próximo viaje?",
    "quiero viajar, ¿qué debo saber?",
    "sugerencias para ahorrar en viajes",
    "¿cómo organizo un viaje?",
    "tips para viajar seguro",
    "quiero viajar al extranjero, ayúdame",
  ],
  tech_news: [
    "dime lo último en tecnología",
    "¿cuáles son las tendencias tecnológicas actuales?",
    "novedades del mundo tech",
    "cuéntame algo sobre tecnología",
    "quiero saber de gadgets nuevos",
  ],
  mindfulness_tips: [
    "dame consejos para relajarme",
    "¿cómo practico mindfulness?",
    "quiero aprender a meditar",
    "¿qué hago para reducir el estrés?",
    "tips para estar más presente",
  ],
  book_recommendations: [
    "recomiéndame un libro",
    "quiero leer algo interesante",
    "¿qué libro me sugieres?",
    "dame ideas de lectura",
    "sugerencias de libros por favor",
  ],
  pet_care: [
    "dame consejos para cuidar a mi mascota",
    "¿cómo cuido a un perro?",
    "quiero adoptar una mascota, ¿qué debo saber?",
    "¿cómo cuido a un gato?",
    "tips para mascotas",
    "cuidados básicos para animales",
  ],
  movie_recommendations: [
    "recomiéndame una película",
    "quiero ver algo bueno",
    "¿qué película me sugieres?",
    "dame opciones de películas",
    "sugerencias de cine",
    "¿qué ver en Netflix?",
  ],
  DIY_projects: [
    "quiero hacer algo creativo",
    "proyectos DIY fáciles",
    "dame ideas para manualidades",
    "¿qué puedo construir en casa?",
    "enséñame un proyecto casero",
    "quiero hacer algo con mis manos",
  ],
  financial_advice: [
    "dame consejos para ahorrar dinero",
    "¿cómo gestiono mis finanzas?",
    "quiero aprender sobre inversiones",
    "tips para organizar mi dinero",
    "¿cómo puedo gastar menos?",
    "quiero mejorar mi situación económica",
  ],
  life_hacks: [
    "dame trucos para la vida diaria",
    "¿qué hacks tienes para facilitar la vida?",
    "quiero aprender algo útil",
    "dame un truco práctico",
    "trucos para mejorar mi rutina",
  ],
  gardening_tips: [
    "¿cómo cuido plantas en casa?",
    "dame consejos de jardinería",
    "quiero aprender a plantar algo",
    "¿cómo cultivo un huerto?",
    "tips para cuidar mis plantas",
    "quiero empezar un jardín",
  ],
  current_events: [
    "¿qué está pasando en el mundo?",
    "dame las últimas noticias",
    "¿qué hay de nuevo hoy?",
    "quiero saber de actualidad",
    "¿qué noticias tienes?",
  ],
  cooking_recipes: [
    "dame una receta fácil",
    "¿qué puedo cocinar hoy?",
    "quiero aprender a cocinar algo nuevo",
    "recetas rápidas y fáciles",
    "¿cómo hago un postre sencillo?",
    "enséñame una receta de cena",
    "quiero sorprender con mi cocina",
  ],
  exercise_ideas: [
    "¿qué ejercicios puedo hacer en casa?",
    "rutinas de ejercicios fáciles",
    "quiero ponerme en forma, ayúdame",
    "dame una rutina para principiantes",
    "¿cómo puedo empezar a hacer ejercicio?",
    "quiero ideas para entrenar sin equipo",
    "ejercicios para mejorar mi salud",
  ],
  motivational_quotes: [
    "dame una frase motivadora",
    "quiero algo inspirador",
    "necesito motivación",
    "¿tienes algo para inspirarme?",
    "dime algo positivo",
    "quiero empezar el día con ánimo",
    "motívame con algo bueno",
  ],
  parenting_tips: [
    "dame consejos para criar a mi hijo",
    "¿cómo ser un mejor padre?",
    "tips para manejar a un adolescente",
    "quiero aprender sobre crianza",
    "¿cómo puedo ser un buen ejemplo para mis hijos?",
    "ayúdame con problemas familiares",
    "dame ideas para fortalecer la relación con mis hijos",
  ],
  learning_resources: [
    "quiero aprender algo nuevo",
    "dame recursos educativos",
    "¿dónde puedo estudiar en línea?",
    "recomendaciones para aprender habilidades",
    "quiero mejorar mis conocimientos",
    "dame cursos gratuitos",
    "quiero saber cómo aprender rápido",
  ],
  tech_troubleshooting: [
    "mi computadora no enciende, ¿qué hago?",
    "ayuda con problemas técnicos",
    "quiero arreglar mi teléfono",
    "¿cómo soluciono un error en mi software?",
    "dame pasos para reparar algo técnico",
    "mi dispositivo no responde, ayúdame",
    "quiero mejorar el rendimiento de mi computadora",
  ],
};

export { intents };
