const intents = {
  greeting: ['hola', 'buenos días', 'buenas tardes', 'buenas noches', 'qué tal', 'hola, ¿cómo estás?'],
  goodbye: ['adiós', 'hasta luego', 'nos vemos', 'chau', 'hasta la próxima'],
  thanks: ['gracias', 'muchas gracias', 'te lo agradezco', 'muchísimas gracias'],
  small_talk: [
    '¿cómo estás?',
    '¿qué tal?',
    '¿qué haces?',
    'cuéntame algo',
    '¿cómo va tu día?',
  ],
  hobbies: [
    '¿cuáles son tus hobbies?',
    '¿qué te gusta hacer?',
    '¿tienes algún pasatiempo?',
    '¿qué haces en tu tiempo libre?',
  ],
  favorite_food: [
    '¿cuál es tu comida favorita?',
    '¿qué te gusta comer?',
    '¿tienes algún plato favorito?',
    '¿qué comida prefieres?',
  ],
  favorite_movie: [
    '¿cuál es tu película favorita?',
    '¿qué películas te gustan?',
    '¿tienes alguna película favorita?',
    '¿qué película me recomiendas?',
  ],
  favorite_music: [
    '¿qué tipo de música te gusta?',
    '¿cuál es tu canción favorita?',
    '¿tienes algún artista favorito?',
    '¿qué música prefieres?',
  ],
  weather: [
    '¿cómo está el clima?',
    '¿qué tiempo hace?',
    '¿va a llover hoy?',
    '¿cómo estará el clima mañana?',
  ],
  jokes: [
    'cuéntame un chiste',
    'dime algo gracioso',
    '¿sabes algún chiste?',
    'hazme reír',
  ],
  advice: [
    'dame un consejo',
    '¿tienes algún consejo para mí?',
    'necesito un consejo',
    '¿qué me recomiendas?',
  ],
  motivation: [
    'dame una frase motivadora',
    'necesito motivación',
    'anímame',
    'dime algo inspirador',
  ],
  personal_life: [
    'cuéntame sobre ti',
    '¿quién eres?',
    'háblame de ti',
    '¿qué haces?',
    '¿cuál es tu historia?',
  ],
  travel: [
    '¿te gusta viajar?',
    '¿cuál es tu destino de viaje favorito?',
    '¿has viajado alguna vez?',
    '¿dónde te gustaría ir?',
    '¿cuál es el mejor lugar para visitar?',
  ],
  books: [
    '¿cuál es tu libro favorito?',
    '¿qué libros te gustan?',
    '¿tienes algún autor favorito?',
    '¿qué libro me recomiendas?',
    '¿te gusta leer?',
  ],
  sports: [
    '¿te gustan los deportes?',
    '¿cuál es tu deporte favorito?',
    '¿practicas algún deporte?',
    '¿qué equipo te gusta?',
    '¿ves deportes?',
  ],
  technology: [
    '¿te gusta la tecnología?',
    '¿cuál es tu gadget favorito?',
    '¿qué opinas de la inteligencia artificial?',
    '¿te gustan los videojuegos?',
    '¿cuál es tu aplicación favorita?',
  ],
  pets: [
    '¿te gustan los animales?',
    '¿tienes mascotas?',
    '¿cuál es tu animal favorito?',
    '¿te gustan los perros o los gatos?',
    '¿cómo se llama tu mascota?',
  ],
  health: [
    '¿cómo te cuidas?',
    '¿tienes algún consejo de salud?',
    '¿haces ejercicio?',
    '¿qué opinas de la alimentación saludable?',
    '¿cómo manejas el estrés?',
  ],
  education: [
    '¿qué estudiaste?',
    '¿te gusta aprender?',
    '¿cuál es tu materia favorita?',
    '¿tienes algún consejo para estudiar?',
    '¿qué opinas de la educación en línea?',
  ],
  news: [
    '¿qué opinas de las noticias actuales?',
    '¿lees las noticias?',
    '¿qué piensas sobre la política?',
    '¿qué opinas del cambio climático?',
    '¿qué piensas sobre la economía?',
  ],
  entertainment: [
    '¿qué te gusta hacer para divertirte?',
    '¿cuál es tu programa de televisión favorito?',
    '¿te gustan los videojuegos?',
    '¿qué haces en tu tiempo libre?',
    '¿te gusta ir al cine?',
  ],
  art: [
    '¿te gusta el arte?',
    '¿cuál es tu artista favorito?',
    '¿te gusta pintar o dibujar?',
    '¿has visitado algún museo recientemente?',
    '¿qué tipo de arte prefieres?',
  ],
  history: [
    '¿te gusta la historia?',
    '¿cuál es tu periodo histórico favorito?',
    '¿tienes algún personaje histórico favorito?',
    '¿qué opinas de la historia antigua?',
    '¿te gusta aprender sobre diferentes culturas?',
  ],
  science: [
    '¿te gusta la ciencia?',
    '¿cuál es tu rama de la ciencia favorita?',
    '¿qué opinas de los avances científicos recientes?',
    '¿tienes algún científico favorito?',
    '¿te gusta la astronomía?',
  ],
  relationships: [
    '¿tienes pareja?',
    '¿qué opinas sobre las relaciones a distancia?',
    '¿tienes algún consejo para mantener una buena relación?',
    '¿qué es lo más importante en una relación?',
    '¿cómo manejas los conflictos en una relación?',
  ],
  career: [
    '¿en qué trabajas?',
    '¿te gusta tu trabajo?',
    '¿tienes algún consejo para avanzar en la carrera?',
    '¿cuál es tu trabajo soñado?',
    '¿cómo manejas el estrés laboral?',
  ],
  goals: [
    '¿cuáles son tus metas?',
    '¿tienes algún objetivo a corto plazo?',
    '¿cómo planeas alcanzar tus metas?',
    '¿qué te motiva a seguir adelante?',
    '¿tienes algún sueño que quieras cumplir?',
  ],
};

export { intents };