export const intents = {
  es: {
    greeting: ['hola', 'buenos días', 'buenas tardes', 'buenas noches', 'qué tal', 'hola, ¿cómo estás?', 'hola, ¿qué tal?', 'hola, ¿cómo va todo?'],
    goodbye: ['adiós', 'hasta luego', 'nos vemos', 'chau', 'hasta la próxima', 'me despido', 'hasta pronto', 'cuídate'],
    thanks: ['gracias', 'muchas gracias', 'te lo agradezco', 'muchísimas gracias', 'mil gracias', 'gracias por tu ayuda', 'gracias por todo'],
    small_talk: ['¿cómo estás?', '¿qué tal?', '¿qué haces?', 'cuéntame algo', '¿cómo va tu día?', '¿qué planes tienes para hoy?', '¿cómo te sientes?', '¿qué hay de nuevo?'],
    hobbies: ['¿cuáles son tus hobbies?', '¿qué te gusta hacer?', '¿tienes algún pasatiempo?', '¿qué haces en tu tiempo libre?', '¿qué te apasiona?', '¿qué actividades disfrutas?', '¿qué te gusta hacer para divertirte?'],
    favorite_food: ['¿cuál es tu comida favorita?', '¿qué te gusta comer?', '¿tienes algún plato favorito?', '¿qué comida prefieres?', '¿cuál es tu postre favorito?', '¿qué tipo de comida te gusta?', '¿te gusta la comida rápida?'],
    favorite_movie: ['¿cuál es tu película favorita?', '¿qué películas te gustan?', '¿tienes alguna película favorita?', '¿qué película me recomiendas?', '¿cuál es tu género de cine favorito?', '¿te gustan las películas de acción?', '¿cuál es la última película que viste?'],
    favorite_music: ['¿qué tipo de música te gusta?', '¿cuál es tu canción favorita?', '¿tienes algún artista favorito?', '¿qué música prefieres?', '¿te gusta la música clásica?', '¿cuál es tu banda favorita?', '¿qué género musical te gusta más?'],
    weather: ['¿cómo está el clima?', '¿qué tiempo hace?', '¿va a llover hoy?', '¿cómo estará el clima mañana?', '¿hace frío?', '¿hace calor?', '¿necesito un paraguas hoy?'],
    jokes: ['cuéntame un chiste', 'dime algo gracioso', '¿sabes algún chiste?', 'hazme reír', 'cuéntame algo divertido', 'dime un chiste corto', '¿tienes algún chiste?'],
    advice: ['dame un consejo', '¿tienes algún consejo para mí?', 'necesito un consejo', '¿qué me recomiendas?', '¿qué debería hacer?', 'dame un buen consejo', '¿tienes algún tip?'],
    motivation: ['dame una frase motivadora', 'necesito motivación', 'anímame', 'dime algo inspirador', 'dame una cita motivacional', 'necesito inspiración', 'motívame'],
    personal_life: ['cuéntame sobre ti', '¿quién eres?', 'háblame de ti', '¿qué haces?', '¿cuál es tu historia?', '¿cómo es tu vida?', '¿qué te gusta hacer en tu tiempo libre?'],
    travel: ['¿te gusta viajar?', '¿cuál es tu destino de viaje favorito?', '¿has viajado alguna vez?', '¿dónde te gustaría ir?', '¿cuál es el mejor lugar para visitar?', '¿qué país te gustaría conocer?', '¿te gusta conocer nuevos lugares?'],
    books: ['¿cuál es tu libro favorito?', '¿qué libros te gustan?', '¿tienes algún autor favorito?', '¿qué libro me recomiendas?', '¿te gusta leer?', '¿qué tipo de libros te gustan?', '¿cuál es el último libro que leíste?'],
    sports: ['¿te gustan los deportes?', '¿cuál es tu deporte favorito?', '¿practicas algún deporte?', '¿qué equipo te gusta?', '¿ves deportes?', '¿te gusta el fútbol?', '¿cuál es tu jugador favorito?'],
    technology: ['¿te gusta la tecnología?', '¿cuál es tu gadget favorito?', '¿qué opinas de la inteligencia artificial?', '¿te gustan los videojuegos?', '¿cuál es tu aplicación favorita?', '¿qué opinas de los avances tecnológicos?', '¿te gusta estar al día con la tecnología?'],
    pets: ['¿te gustan los animales?', '¿tienes mascotas?', '¿cuál es tu animal favorito?', '¿te gustan los perros o los gatos?', '¿cómo se llama tu mascota?', '¿te gustaría tener una mascota?', '¿cuál es tu raza de perro favorita?'],
    health: ['¿cómo te cuidas?', '¿tienes algún consejo de salud?', '¿haces ejercicio?', '¿qué opinas de la alimentación saludable?', '¿cómo manejas el estrés?', '¿te gusta hacer deporte?', '¿tienes algún hábito saludable?'],
    education: ['¿qué estudiaste?', '¿te gusta aprender?', '¿cuál es tu materia favorita?', '¿tienes algún consejo para estudiar?', '¿qué opinas de la educación en línea?', '¿te gusta ir a la escuela?', '¿cuál es tu asignatura favorita?'],
    news: ['¿qué opinas de las noticias actuales?', '¿lees las noticias?', '¿qué piensas sobre la política?', '¿qué opinas del cambio climático?', '¿qué piensas sobre la economía?', '¿te gusta estar informado?', '¿qué opinas de las noticias internacionales?'],
    entertainment: ['¿qué te gusta hacer para divertirte?', '¿cuál es tu programa de televisión favorito?', '¿te gustan los videojuegos?', '¿qué haces en tu tiempo libre?', '¿te gusta ir al cine?', '¿cuál es tu serie favorita?', '¿qué tipo de entretenimiento prefieres?'],
  },
  en: {
    greeting: ['hello', 'good morning', 'good afternoon', 'good evening', 'how are you', 'hi, how are you?', 'hi there', 'hey, how are you?'],
    goodbye: ['goodbye', 'see you later', 'see you', 'bye', 'until next time', 'take care', 'catch you later', 'farewell'],
    thanks: ['thank you', 'thanks a lot', 'I appreciate it', 'thank you very much', 'many thanks', 'thanks for your help', 'thanks for everything'],
    small_talk: ['how are you?', 'what’s up?', 'what are you doing?', 'tell me something', 'how’s your day going?', 'any plans for today?', 'how do you feel?', 'what’s new?'],
    hobbies: ['what are your hobbies?', 'what do you like to do?', 'do you have any hobbies?', 'what do you do in your free time?', 'what are you passionate about?', 'what activities do you enjoy?', 'what do you like to do for fun?'],
    favorite_food: ['what’s your favorite food?', 'what do you like to eat?', 'do you have a favorite dish?', 'what food do you prefer?', 'what’s your favorite dessert?', 'what kind of food do you like?', 'do you like fast food?'],
    favorite_movie: ['what’s your favorite movie?', 'what movies do you like?', 'do you have a favorite movie?', 'what movie do you recommend?', 'what’s your favorite film genre?', 'do you like action movies?', 'what’s the last movie you watched?'],
    favorite_music: ['what kind of music do you like?', 'what’s your favorite song?', 'do you have a favorite artist?', 'what music do you prefer?', 'do you like classical music?', 'what’s your favorite band?', 'what’s your favorite music genre?'],
    weather: ['how’s the weather?', 'what’s the weather like?', 'is it going to rain today?', 'how will the weather be tomorrow?', 'is it cold?', 'is it hot?', 'do I need an umbrella today?'],
    jokes: ['tell me a joke', 'say something funny', 'do you know any jokes?', 'make me laugh', 'tell me something funny', 'tell me a short joke', 'do you have any jokes?'],
    advice: ['give me some advice', 'do you have any advice for me?', 'I need some advice', 'what do you recommend?', 'what should I do?', 'give me a good piece of advice', 'do you have any tips?'],
    motivation: ['give me a motivational quote', 'I need some motivation', 'cheer me up', 'say something inspiring', 'give me a motivational quote', 'I need some inspiration', 'motivate me'],
    personal_life: ['tell me about yourself', 'who are you?', 'tell me about you', 'what do you do?', 'what’s your story?', 'how’s your life?', 'what do you like to do in your free time?'],
    travel: ['do you like to travel?', 'what’s your favorite travel destination?', 'have you ever traveled?', 'where would you like to go?', 'what’s the best place to visit?', 'what country would you like to visit?', 'do you like to explore new places?'],
    books: ['what’s your favorite book?', 'what books do you like?', 'do you have a favorite author?', 'what book do you recommend?', 'do you like to read?', 'what kind of books do you like?', 'what’s the last book you read?'],
    sports: ['do you like sports?', 'what’s your favorite sport?', 'do you play any sports?', 'what’s your favorite team?', 'do you watch sports?', 'do you like soccer?', 'who’s your favorite player?'],
    technology: ['do you like technology?', 'what’s your favorite gadget?', 'what do you think about artificial intelligence?', 'do you like video games?', 'what’s your favorite app?', 'what do you think about technological advancements?', 'do you like to stay updated with technology?'],
    pets: ['do you like animals?', 'do you have pets?', 'what’s your favorite animal?', 'do you like dogs or cats?', 'what’s your pet’s name?', 'would you like to have a pet?', 'what’s your favorite dog breed?'],
    health: ['how do you take care of yourself?', 'do you have any health tips?', 'do you exercise?', 'what do you think about healthy eating?', 'how do you manage stress?', 'do you like to play sports?', 'do you have any healthy habits?'],
    education: ['what did you study?', 'do you like to learn?', 'what’s your favorite subject?', 'do you have any study tips?', 'what do you think about online education?', 'do you like going to school?', 'what’s your favorite class?'],
    news: ['what do you think about current news?', 'do you read the news?', 'what do you think about politics?', 'what do you think about climate change?', 'what do you think about the economy?', 'do you like to stay informed?', 'what do you think about international news?'],
    entertainment: ['what do you like to do for fun?', 'what’s your favorite TV show?', 'do you like video games?', 'what do you do in your free time?', 'do you like going to the movies?', 'what’s your favorite series?', 'what kind of entertainment do you prefer?'],
  }
};