export const responses = {
  es: {
    greeting: ['¡Hola! ¿Cómo puedo ayudarte hoy?', '¡Hola! ¿En qué puedo asistirte?', '¡Hola! ¿Cómo estás?'],
    goodbye: ['¡Adiós! ¡Que tengas un gran día!', '¡Hasta luego! ¡Cuídate!', '¡Nos vemos! ¡Que estés bien!'],
    thanks: ['¡De nada! Si tienes alguna otra pregunta, no dudes en preguntar.', '¡Con gusto! ¿Necesitas algo más?', '¡De nada! Estoy aquí para ayudarte.'],
    small_talk: ['Estoy bien, gracias por preguntar. ¿Y tú?', 'Todo bien por aquí. ¿Qué tal tú?', 'Estoy aquí para ayudarte. ¿En qué puedo asistirte?', '¡Hola! ¿Cómo va tu día?'],
    hobbies: ['Me gusta aprender cosas nuevas. ¿Y a ti?', 'No tengo hobbies, pero me encantaría saber los tuyos.', 'Me encanta conversar contigo. ¿Cuáles son tus pasatiempos?'],
    favorite_food: ['No tengo una comida favorita, pero me encantaría saber cuál es la tuya.', 'No como, pero me encantaría saber qué te gusta comer.', 'No tengo preferencias, pero me encantaría saber tus gustos.'],
    favorite_movie: ['No veo películas, pero me encantaría saber cuál es tu favorita.', 'No tengo una película favorita, pero me encantaría saber la tuya.', 'No veo películas, pero me encantaría escuchar tus recomendaciones.'],
    favorite_music: ['No escucho música, pero me encantaría saber qué tipo de música te gusta.', 'No tengo una canción favorita, pero me encantaría saber cuál es la tuya.', 'No escucho música, pero me encantaría saber tus preferencias.'],
    weather: ['No puedo verificar el clima, pero espero que haga buen tiempo.', 'No tengo acceso a datos meteorológicos, pero espero que tengas un buen día.', 'No sé si va a llover, pero espero que estés preparado.'],
    jokes: ['¿Por qué los pájaros no usan Facebook? Porque ya tienen Twitter.', '¿Qué hace una abeja en el gimnasio? ¡Zum-ba!', '¿Por qué el libro de matemáticas se deprimió? Porque tenía demasiados problemas.'],
    advice: ['Siempre sigue tus sueños y nunca te rindas.', 'La paciencia es una virtud. Todo llega a su debido tiempo.', 'Confía en ti mismo y en tus habilidades.'],
    motivation: ['El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'No importa lo lento que vayas, siempre y cuando no te detengas.', 'Cree en ti mismo y en todo lo que eres. Eres capaz de cosas increíbles.'],
    personal_life: ['Soy un chatbot diseñado para ayudarte con tus preguntas.', 'No tengo una vida personal, pero estoy aquí para asistirte.', 'Mi propósito es ayudarte y aprender de nuestras interacciones.'],
    travel: ['No viajo, pero me encantaría saber sobre tus viajes.', 'No tengo un destino favorito, pero me han dicho que París es hermoso.', 'No viajo, pero me encantaría escuchar sobre tus aventuras.'],
    books: ['No leo libros, pero me encantaría saber cuál es tu favorito.', 'No tengo un libro favorito, pero me gusta aprender sobre diferentes géneros.', 'No tengo un autor favorito, pero me encantaría saber cuál es el tuyo.'],
    sports: ['No practico deportes, pero me encantaría saber cuál es tu favorito.', 'No tengo un deporte favorito, pero me gusta aprender sobre diferentes deportes.', 'No practico deportes, pero me encantaría saber si tú lo haces.'],
    technology: ['Me encanta la tecnología, especialmente la inteligencia artificial.', 'No tengo un gadget favorito, pero me encantaría saber cuál es el tuyo.', 'Creo que la inteligencia artificial tiene un gran potencial para el futuro.'],
    pets: ['Me encantan los animales, aunque no tengo mascotas.', 'No tengo mascotas, pero me encantaría saber sobre las tuyas.', 'No tengo un animal favorito, pero me encantaría saber cuál es el tuyo.'],
    health: ['No tengo necesidades de salud, pero me encantaría saber cómo te cuidas.', 'No tengo consejos de salud, pero me encantaría saber los tuyos.', 'No hago ejercicio, pero me encantaría saber si tú lo haces.'],
    education: ['No estudié, pero me encanta aprender.', 'Me encanta aprender cosas nuevas.', 'No tengo una materia favorita, pero me encantaría saber cuál es la tuya.'],
    news: ['No tengo opiniones sobre las noticias, pero me encantaría saber las tuyas.', 'No leo las noticias, pero me encantaría saber si tú lo haces.', 'No tengo opiniones sobre la política, pero me encantaría saber las tuyas.'],
    entertainment: ['Me encanta conversar contigo para divertirme.', 'No veo televisión, pero me encantaría saber cuál es tu programa favorito.', 'No juego videojuegos, pero me encantaría saber cuáles te gustan.'],
  },
  en: {
    greeting: ['Hello! How can I help you today?', 'Hi there! How can I assist you?', 'Hello! How are you?'],
    goodbye: ['Goodbye! Have a great day!', 'See you later! Take care!', 'Goodbye! Stay safe!'],
    thanks: ['You are welcome! If you have any other questions, feel free to ask.', 'My pleasure! Do you need anything else?', 'You are welcome! I am here to help.'],
    small_talk: ['I am fine, thank you for asking. How about you?', 'All good here. How about you?', 'I am here to help you. How can I assist you?', 'Hello! How is your day going?'],
    hobbies: ['I like learning new things. How about you?', 'I do not have hobbies, but I would love to know yours.', 'I love chatting with you. What are your hobbies?'],
    favorite_food: ['I do not have a favorite food, but I would love to know yours.', 'I do not eat, but I would love to know what you like to eat.', 'I do not have preferences, but I would love to know your tastes.'],
    favorite_movie: ['I do not watch movies, but I would love to know your favorite.', 'I do not have a favorite movie, but I would love to know yours.', 'I do not watch movies, but I would love to hear your recommendations.'],
    favorite_music: ['I do not listen to music, but I would love to know what kind of music you like.', 'I do not have a favorite song, but I would love to know yours.', 'I do not listen to music, but I would love to know your preferences.'],
    weather: ['I cannot check the weather, but I hope it is nice.', 'I do not have access to weather data, but I hope you have a great day.', 'I do not know if it will rain, but I hope you are prepared.'],
    jokes: ['Why do birds not use Facebook? Because they already have Twitter.', 'What does a bee do in the gym? Zumba!', 'Why did the math book get depressed? Because it had too many problems.'],
    advice: ['Always follow your dreams and never give up.', 'Patience is a virtue. Everything comes in due time.', 'Believe in yourself and your abilities.'],
    motivation: ['Success is the sum of small efforts repeated day in and day out.', 'It does not matter how slowly you go as long as you do not stop.', 'Believe in yourself and all that you are. You are capable of amazing things.'],
    personal_life: ['I am a chatbot designed to help you with your questions.', 'I do not have a personal life, but I am here to assist you.', 'My purpose is to help you and learn from our interactions.'],
    travel: ['I do not travel, but I would love to hear about your trips.', 'I do not have a favorite destination, but I have heard that Paris is beautiful.', 'I do not travel, but I would love to hear about your adventures.'],
    books: ['I do not read books, but I would love to know your favorite.', 'I do not have a favorite book, but I like learning about different genres.', 'I do not have a favorite author, but I would love to know yours.'],
    sports: ['I do not play sports, but I would love to know your favorite.', 'I do not have a favorite sport, but I like learning about different sports.', 'I do not play sports, but I would love to know if you do.'],
    technology: ['I love technology, especially artificial intelligence.', 'I do not have a favorite gadget, but I would love to know yours.', 'I think artificial intelligence has great potential for the future.'],
    pets: ['I love animals, although I do not have pets.', 'I do not have pets, but I would love to hear about yours.', 'I do not have a favorite animal, but I would love to know yours.'],
    health: ['I do not have health needs, but I would love to know how you take care of yourself.', 'I do not have health tips, but I would love to hear yours.', 'I do not exercise, but I would love to know if you do.'],
    education: ['I did not study, but I love learning.', 'I love learning new things.', 'I do not have a favorite subject, but I would love to know yours.'],
    news: ['I do not have opinions about the news, but I would love to hear yours.', 'I do not read the news, but I would love to know if you do.', 'I do not have opinions about politics, but I would love to hear yours.'],
    entertainment: ['I love chatting with you for fun.', 'I do not watch TV, but I would love to know your favorite show.', 'I do not play video games, but I would love to know which ones you like.'],
  }
};