FROM python:3.10.12

# Establecer el directorio de trabajo
WORKDIR /app

# Actualizar pip a la versión 24.1.2
RUN pip install --upgrade pip==24.1.2

# Copiar el archivo de requerimientos
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de la aplicación
COPY . .

# Comando por defecto
CMD ["python", "des.py"]